### ISSUE TITLE
ND4S 2.12 errors

### ISSUE THREAD

**Issue by JohnTheDang** [deeplearning4j/nd4s#82] opened 2016-02-11 16:13 UTC
When downloading ND4S via Maven in IntelliJ, there are several versions to pick from. One of them is v2.12 M3 which is unusable for several functions (maybe all).

One example is: 
val arr = (1 to 9).asNDArray(3,3)

which gives a NoSuchMethodException.

**Comment by taisukeoe** [comment] 2016-02-11 17:40
Would you share your minimal project which reproduces that error, with full stack trace?

NoSuchMethodException looks very weird. ND4S in 2.12.0-M3 works well in sbt console as follows:

```
git clone git@github.com:deeplearning4j/nd4s.git
cd nd4s
sbt
sbt> set scalaVersion := "2.12.0-M3"
sbt> test:console

scala> (1 to 9).asNDArray(3,3)
res0: org.nd4j.linalg.api.ndarray.INDArray =
[[1.00,2.00,3.00]
 [4.00,5.00,6.00]
 [7.00,8.00,9.00]]
```

It seems to be due to wrong setting e.g. classpath in IntelliJ.

**Comment by JohnTheDang** [comment] 2016-02-11 23:28
Hi, I am new to using Git, Maven and IntelliJ, so I don't really know what you mean with full stack trace, but I'll attach the content in my pom.xml that I use in IntelliJ that gives this error below my comment. The project is just an ordinary Maven project in IntelliJ with archetype-quickstart. 
You need to add nd4s via Maven in IntelliJ. The version I used was nd4s_2.12.0-M3:0.4-rc3.8

**Comment by JohnTheDang** [comment] 2016-02-11 23:28
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>stud.master_thesis</groupId>
  <artifactId>Nd4j</artifactId>
  <version>1.0-SNAPSHOT</version>
  <packaging>jar</packaging>

  <name>Nd4j</name>
  <url>http://maven.apache.org</url>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <nd4j.version>0.4-rc3.8</nd4j.version>
    <dl4j.version>	0.4-rc3.8</dl4j.version>
    <canova.version>0.0.0.14</canova.version>
    <jackson.version>2.5.1</jackson.version>
  </properties>
  <dependencies>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>3.8.1</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.nd4j</groupId>
      <artifactId>nd4j-x86</artifactId>
      <version>${nd4j.version}</version>
    </dependency>
  </dependencies>

    <repositories>
        <repository>
            <id>snapshots-repo</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots</url>
            <releases><enabled>false</enabled></releases>
            <snapshots><enabled>true</enabled></snapshots>
        </repository>
    </repositories>
</project>

**Comment by JohnTheDang** [comment] 2016-02-11 23:28
> <project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>stud.master_thesis</groupId>
  <artifactId>Nd4j</artifactId>
  <version>1.0-SNAPSHOT</version>
  <packaging>jar</packaging>

  <name>Nd4j</name>
  <url>http://maven.apache.org</url>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <nd4j.version>0.4-rc3.8</nd4j.version>
    <dl4j.version>	0.4-rc3.8</dl4j.version>
    <canova.version>0.0.0.14</canova.version>
    <jackson.version>2.5.1</jackson.version>
  </properties>
  <dependencies>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>3.8.1</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.nd4j</groupId>
      <artifactId>nd4j-x86</artifactId>
      <version>${nd4j.version}</version>
    </dependency>
  </dependencies>

    <repositories>
        <repository>
            <id>snapshots-repo</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots</url>
            <releases><enabled>false</enabled></releases>
            <snapshots><enabled>true</enabled></snapshots>
        </repository>
    </repositories>
</project>

>

**Comment by JohnTheDang** [comment] 2016-02-11 23:30
Couldn't send it as an xml file, so I send it as a txt, though the content is just the pom.xml that I use.
[pom.txt](https://github.com/deeplearning4j/nd4s/files/127264/pom.txt)

**Comment by JohnTheDang** [comment] 2016-02-11 23:39
Oh, wait, sorry, could it be so that I have to use the same nd4s version as my scala verion, i.e. I have scala version 2.11.7, so I have to have nd4s_2.11:0.4-rc3.8 instead of nd4s_2.12.0-M3:0.4-rc3.8?

**Comment by taisukeoe** [comment] 2016-02-11 23:46
@JohnTheDang 
Exactly.
Scala different major versions are binary incompatible,and cannot be mixed in a project. For example, Scala 2.11.x and Scala 2.12.x are binary incompatible.

In case you use Scala 2.11.7 in your project, you have to use nd4s_2.11, not nd4s_2.12.0-M3.

**Comment by JohnTheDang** [comment] 2016-02-12 00:01
All right! Then I understand! Thank you very much for all the help! Btw, when will the fix you implemented for the overloading + methods get into the maven repository? For now I was able to compile a new .jar for the updated snapshot, though the process a lot easier if the fix was in Maven.

**Comment by taisukeoe** [comment] 2016-02-12 00:07
It depends on when deeplearning4j / nd4j 0.4-rc3.9 will be released.

@agibsonccc Do you have any target date in your mind?

**Comment by taisukeoe** [comment] 2016-02-18 13:47
Since Original problem has been already resolved, let me close this issue.

**Closed by taisukeoe** 2016-02-18 13:47 UTC
